-- ==========================================================================
-- Author                 : RUA, Sweco
-- Create date            : 2019-06-10
-- Updated                : $Date: 2019-08-30 15:10:45 +0200 (fr, 30 aug 2019) $
-- Updated by             : $Author: rua $
-- Description            : Metadata for temaer i RIT
-- ==========================================================================
DECLARE @svn_revision	varchar(15)	= '$Rev: 1948 $'
DECLARE @db_version		varchar(15)	= '1.0'
DECLARE @scriptnavn		varchar(60)	= '006 TemaMetaData.sql'
DECLARE @beskrivelse	varchar(250)= 'Metadata for temaer i RIT'

INSERT INTO script_log (db_version,dato,scriptnavn,beskrivelse,svn_revision)
VALUES  (@db_version,getdate(),@scriptnavn,@beskrivelse,@svn_revision);
GO

set nocount on;
go

-------------------------------------------------------------------------------------------------------
-- *********************************
-- SCRIPTET SKAL KØRES I CMDMODE
-- *********************************

:SETVAR RegionKode "-1" -- Regionkode 

--   -1 Sweco (alle)
--  400 Bornholms Regionskommune
-- 1081 Region Nordjylland
-- 1082 Region Midtjylland
-- 1083 Region Syddanmark
-- 1084 Region Hovedstaden
-- 1085 Region Sjælland


-------------------------------------------------------------------------------------------------------
-- Nedenstående er data importeret fra Excel dokumkent udarbejdet af Peter Riis (Reg.Sj)
-- Det danner udgangspunkt for de temaer der ønskes lagt i temadatabasen.

-- Temaerne er som udgangspuntk sat til ISVALID=0, eftersom der ingen data er i temadatabasen på nuværende tidspunkt.

-------------------------------------------------------------------------------------------------------
PRINT '---------------------------------------------'
PRINT 'Input Regionskode: $(RegionKode)'
PRINT '---------------------------------------------'
-------------------------------------------------------------------------------------------------------
-- TEMA: Kommunegrænser

-- GRUPPE: Admin. grænser
DECLARE @ID						UNIQUEIDENTIFIER= 'EA4ADE67-D98E-4E7B-BEDB-22C63F704B46';
DECLARE @GRUPPE					VARCHAR(100)	= 'Admin. grænser';
DECLARE @TEMA					VARCHAR(100)	= 'Kommunegrænser';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kommunegrænser';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'KMS';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'ftp://gmcb3:3bcmg@ftp.kortforsyningen.dk/landinddelinger/dagi/SHAPE/DAGIREF_SHAPE_UTM32-EUREF89.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kommune';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'komnavn';
DECLARE @ISVALID				BIT				= 0;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 365;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='8EF41FF3-10AD-46B0-A15B-E95E331298E4'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Admin. grænser: Kommunegrænser'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO

-------------------------------------------------------------------------------------------------------
-- TEMA: Kystnærhedszonen (linje)

-- GRUPPE: Bygge- og beskyttelseslinjer
DECLARE @ID						UNIQUEIDENTIFIER= '8EF41FF3-10AD-46B0-A15B-E95E331298E4';
DECLARE @GRUPPE					VARCHAR(100)	= 'Bygge- og beskyttelseslinjer';
DECLARE @TEMA					VARCHAR(100)	= 'Kystnærhedszonen (linje)';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kystnærhedszone - linje
KYSTNAERHEDSZONE';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KYSTNAERHEDSZONE_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kystnaerhedszone';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='8EF41FF3-10AD-46B0-A15B-E95E331298E4'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Bygge- og beskyttelseslinjer: Kystnærhedszonen (linje)'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Skovbyggelinier

-- GRUPPE: Bygge- og beskyttelseslinjer
DECLARE @ID						UNIQUEIDENTIFIER= '459C52DB-D37D-4534-81E9-0A4586813A71';
DECLARE @GRUPPE					VARCHAR(100)	= 'Bygge- og beskyttelseslinjer';
DECLARE @TEMA					VARCHAR(100)	= 'Skovbyggelinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Skovbyggelinjer - flade
SKOVBYGGELINJER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/SKOVBYGGELINJER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'skovbyggelinjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='459C52DB-D37D-4534-81E9-0A4586813A71'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Bygge- og beskyttelseslinjer: Skovbyggelinier'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Søbeskyttelseslinier

-- GRUPPE: Bygge- og beskyttelseslinjer
DECLARE @ID						UNIQUEIDENTIFIER= '8AC6787C-EBDE-41C1-9915-94079EAD5950';
DECLARE @GRUPPE					VARCHAR(100)	= 'Bygge- og beskyttelseslinjer';
DECLARE @TEMA					VARCHAR(100)	= 'Søbeskyttelseslinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Søbeskyttelseslinier
SOE_BES_LINJER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/SOE_BES_LINJER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'soe_bes_linjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='8AC6787C-EBDE-41C1-9915-94079EAD5950'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Bygge- og beskyttelseslinjer: Søbeskyttelseslinier'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Åbeskyttelseslinier

-- GRUPPE: Bygge- og beskyttelseslinjer
DECLARE @ID						UNIQUEIDENTIFIER= '67FB1C9D-3483-40A8-9D80-D830FB409E04';
DECLARE @GRUPPE					VARCHAR(100)	= 'Bygge- og beskyttelseslinjer';
DECLARE @TEMA					VARCHAR(100)	= 'Åbeskyttelseslinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Åbeskyttelseslinjer - flade
AA_BES_LINJER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/AA_BES_LINJER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'aa_bes_linjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='67FB1C9D-3483-40A8-9D80-D830FB409E04'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Bygge- og beskyttelseslinjer: Åbeskyttelseslinier'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Beskyttede Sten og jorddiger

-- GRUPPE: Fortidsminder og kulturarv
DECLARE @ID						UNIQUEIDENTIFIER= 'A546963E-AAB4-40C9-ADED-5FB73F0BB9F1';
DECLARE @GRUPPE					VARCHAR(100)	= 'Fortidsminder og kulturarv';
DECLARE @TEMA					VARCHAR(100)	= 'Beskyttede Sten og jorddiger';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Beskyttede Sten og jorddiger
BES_STEN_JORDDIGER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/BES_STEN_JORDDIGER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'bes_sten_jorddiger';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='A546963E-AAB4-40C9-ADED-5FB73F0BB9F1'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Fortidsminder og kulturarv: Beskyttede Sten og jorddiger'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Kirkebyggelinier

-- GRUPPE: Fortidsminder og kulturarv
DECLARE @ID						UNIQUEIDENTIFIER= '430E5D6C-74A1-47C1-920F-8678641572FB';
DECLARE @GRUPPE					VARCHAR(100)	= 'Fortidsminder og kulturarv';
DECLARE @TEMA					VARCHAR(100)	= 'Kirkebyggelinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kirkebyggelinjer - flade
KIRKEBYGGELINJER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KIRKEBYGGELINJER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'Kirkebyggelinjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='430E5D6C-74A1-47C1-920F-8678641572FB'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Fortidsminder og kulturarv: Kirkebyggelinier'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Fredede områder

-- GRUPPE: Fredninger
DECLARE @ID						UNIQUEIDENTIFIER= '4D55610B-F9F7-4DCC-922B-D8E1BA21D924';
DECLARE @GRUPPE					VARCHAR(100)	= 'Fredninger';
DECLARE @TEMA					VARCHAR(100)	= 'Fredede områder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Fredede områder - flade
FREDEDE_OMR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/FREDEDE_OMR_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'fredede_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'fred_navn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='4D55610B-F9F7-4DCC-922B-D8E1BA21D924'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Fredninger: Fredede områder'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Fredede områder forslag

-- GRUPPE: Fredninger
DECLARE @ID						UNIQUEIDENTIFIER= '06CF454B-9C59-45ED-89D7-6A9355EF5AF7';
DECLARE @GRUPPE					VARCHAR(100)	= 'Fredninger';
DECLARE @TEMA					VARCHAR(100)	= 'Fredede områder forslag';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Fredede områder, forslag - flade
FREDEDE_OMR_FORSLAG';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/FREDEDE_OMR_FORSLAG_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'fredede_omr_forslag';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'fred_navn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='06CF454B-9C59-45ED-89D7-6A9355EF5AF7'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Fredninger: Fredede områder forslag'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Områdeklassificering 

-- GRUPPE: Jordforurening
DECLARE @ID						UNIQUEIDENTIFIER= 'E1A432D7-3504-4056-B567-56CD6A20D7F0';
DECLARE @GRUPPE					VARCHAR(100)	= 'Jordforurening';
DECLARE @TEMA					VARCHAR(100)	= 'Områdeklassificering ';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Områdeklassificering - flade
OMR_KLASSIFICERING';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OMR_KLASSIFICERING_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'omr_klassificering';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'ana_krnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='E1A432D7-3504-4056-B567-56CD6A20D7F0'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Jordforurening: Områdeklassificering '
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Beskyttede naturtyper

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= 'C34E5B00-5319-410E-9EA6-96808DE27DEA';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'Beskyttede naturtyper';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Beskyttede naturtyper - flade
BES_NATURTYPER';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/BES_NATURTYPER_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'bes_naturtyper';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'natyp_navn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='C34E5B00-5319-410E-9EA6-96808DE27DEA'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: Beskyttede naturtyper'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Beskyttede vandløb

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= 'CFEA0961-DF74-4C6C-8E37-95ECE4F92529';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'Beskyttede vandløb';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Beskyttede vandløb - linje
BES_VANDLOEB';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/BES_VANDLOEB_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'bes_vandloeb';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'temanavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='CFEA0961-DF74-4C6C-8E37-95ECE4F92529'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: Beskyttede vandløb'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: EF fuglebeskyttelsesområder

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= '80B5820C-3C4A-4243-9168-2FEE4E7A15E1';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'EF fuglebeskyttelsesområder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'EF fuglebeskyttelsesområder
FUGLE_BES_OMR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/FUGLE_BES_OMR_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'fugle_bes_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'objektnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='80B5820C-3C4A-4243-9168-2FEE4E7A15E1'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: EF fuglebeskyttelsesområder'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: EF habitatområder

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= 'F4963A9C-6A1A-4D5C-B24B-FF25CA74E03C';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'EF habitatområder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'EF habitatområder
HABITAT_OMR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/HABITAT_OMR_MITAB.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'EUHabitatomraader';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'objektnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='F4963A9C-6A1A-4D5C-B24B-FF25CA74E03C'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: EF habitatområder'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Natur- og vildtreservater

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= '7589A250-D475-48BC-8A8A-622E6E5B9261';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'Natur- og vildtreservater';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Natur- og vildtreservater - flade
NATUR_VILDT_RESERVAT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/NATUR_VILDT_RESERVAT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'natur_vildt_reservat';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'res_tnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='7589A250-D475-48BC-8A8A-622E6E5B9261'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: Natur- og vildtreservater'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Ramsar områder

-- GRUPPE: Naturbeskyttelse og Natura 2000
DECLARE @ID						UNIQUEIDENTIFIER= '16AED897-4F34-46B5-99E8-A997C0AEECA9';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturbeskyttelse og Natura 2000';
DECLARE @TEMA					VARCHAR(100)	= 'Ramsar områder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Ramsar områder 
RAMSAR_OMR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/RAMSAR_OMR_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'ramsar_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'objektnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=1, RNord=1, RMidt=1, RSyd=1, RHoved=1, RSjael=1 WHERE TemaId='16AED897-4F34-46B5-99E8-A997C0AEECA9'

IF ($(RegionKode) IN (-1,400,1081,1082,1083,1084,1085))
BEGIN
    PRINT 'Naturbeskyttelse og Natura 2000: Ramsar områder'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Generelle artsfund, flade

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '91B9C987-9A38-4529-AB0F-7DF16920144C';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Generelle artsfund, flade';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Generelle artsfund - flader
GEN_ARTSFUND_FL';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/GEN_ARTSFUND_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'gen_artsfund_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'stednavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='91B9C987-9A38-4529-AB0F-7DF16920144C'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Generelle artsfund, flade'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Generelle artsfund, linje

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '1AD8716D-1587-434D-B0BA-73CD5FB5D025';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Generelle artsfund, linje';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Generelle artsfund - linjer
GEN_ARTSFUND_LN';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/GEN_ARTSFUND_LN_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'gen_artsfund_ln';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'stednavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='1AD8716D-1587-434D-B0BA-73CD5FB5D025'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Generelle artsfund, linje'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Generelle artsfund, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '8B278E81-ED8D-4E8C-AEA7-638FDF134FDA';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Generelle artsfund, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Generelle artsfund - punkter
GEN_ARTSFUND_PKT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/GEN_ARTSFUND_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'gen_artsfund_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='8B278E81-ED8D-4E8C-AEA7-638FDF134FDA'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Generelle artsfund, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Kortlægning af levesteder, flade

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= 'B01FBCF2-982B-4ED9-A4CD-50B040FF261F';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Kortlægning af levesteder, flade';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kortlægning af levesteder - flade
KORTLAEG_LEVESTEDER_FL';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KORTLAEG_LEVESTEDER_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kortlaeg_levesteder_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='B01FBCF2-982B-4ED9-A4CD-50B040FF261F'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Kortlægning af levesteder, flade'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Kortlægning af levesteder, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '05C5FE4A-B76A-4A29-874E-B4A9E92DEAEE';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Kortlægning af levesteder, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '?Kortlægning af levesteder - punkter
KORTLAEG_LEVESTEDER_PKT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KORTLAEG_LEVESTEDER_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kortlaeg_levesteder_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'stednavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='05C5FE4A-B76A-4A29-874E-B4A9E92DEAEE'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Kortlægning af levesteder, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Kortlægning af naturtyper, flade

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '3AA159A4-F2AB-406A-8BF9-0711217A49A8';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Kortlægning af naturtyper, flade';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kortlægning af naturtyper - flader
KORTLAEG_NATURTYPER_FL_SHAPE';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KORTLAEG_NATURTYPER_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kortlaeg_naturtyper_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'naturtype';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='3AA159A4-F2AB-406A-8BF9-0711217A49A8'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Kortlægning af naturtyper, flade'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Kortlægning af naturtyper, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '8E9DF2B3-5426-4ABF-A646-B31D8428A285';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Kortlægning af naturtyper, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Kortlægning af naturtyper - punkter
KORTLAEG_NATURTYPER_PKT_SHAPE';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/KORTLAEG_NATURTYPER_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kortlaeg_naturtyper_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='8E9DF2B3-5426-4ABF-A646-B31D8428A285'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Kortlægning af naturtyper, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Natur besigtigelse, flade

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '444F8A83-0DEA-4C39-8E19-25E865C2C887';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Natur besigtigelse, flade';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Naturbesigtigelse - flade
NAT_BESIGTIGELSER_FL_SHAPE';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/NAT_BESIGTIGELSER_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'nat_besigtigelser_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'naturtype';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='444F8A83-0DEA-4C39-8E19-25E865C2C887'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Natur besigtigelse, flade'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Natur besigtigelse, Linje

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '85CC9D63-D6E9-487A-9D30-6F8DA857FEC8';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Natur besigtigelse, Linje';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Naturbesigtigelse - linjer
NAT_BESIGTIGELSER_LN';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/NAT_BESIGTIGELSER_LN_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'nat_besigtigelser_ln';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'stednavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='85CC9D63-D6E9-487A-9D30-6F8DA857FEC8'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Natur besigtigelse, Linje'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Natur besigtigelse, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= 'EC1CC9D3-824A-4587-88A6-B409D5A4C794';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Natur besigtigelse, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Naturbesigtigelse - punkter
NAT_BESIGTIGELSER_PKT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/NAT_BESIGTIGELSER_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'nat_besigtigelser_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'stednavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='EC1CC9D3-824A-4587-88A6-B409D5A4C794'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Natur besigtigelse, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Overvågning af bilagsarter, flade

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '1AA24D38-73C4-4E91-AC0E-52591ECB9655';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Overvågning af bilagsarter, flade';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Overvågning af bilagsarter mm. - flade
OVERVAAGN_BILAGSARTER_FL';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OVERVAAGN_BILAGSARTER_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'overvaagn_bilagsarter_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190823';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='1AA24D38-73C4-4E91-AC0E-52591ECB9655'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Overvågning af bilagsarter, flade'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Overvågning af bilagsarter, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '7FBCFCE0-7B69-4ECF-A134-B6373ED2ECDA';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Overvågning af bilagsarter, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Overvågning af bilagsarter mm. - punkter
OVERVAAGN_BILAGSARTER_PKT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OVERVAAGN_BILAGSARTER_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'overvaagn_bilagsarter_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='7FBCFCE0-7B69-4ECF-A134-B6373ED2ECDA'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Overvågning af bilagsarter, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Overvågning af fugle, flader

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '85ECF841-B5AB-4BA7-9BAD-61F80CE89A23';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Overvågning af fugle, flader';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Overvågning af fugle - flade
OVERVAAGN_FUGLE_FL';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OVERVAAGN_FUGLE_FL_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'overvaagn_fugle_fl';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= null;
DECLARE @ISVALID				BIT				= 0;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='85ECF841-B5AB-4BA7-9BAD-61F80CE89A23'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Overvågning af fugle, flader'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Overvågning af fugle, linjer

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= 'FC68B309-3F8C-4BBD-97AA-A8217D0150AE';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Overvågning af fugle, linjer';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Overvågning af fugle - linjer
OVERVAAGN_FUGLE_LN';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OVERVAAGN_FUGLE_LN_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'overvaagn_fugle_ln';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='FC68B309-3F8C-4BBD-97AA-A8217D0150AE'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Overvågning af fugle, linjer'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: Overvågning af fugle, punkt

-- GRUPPE: Naturdata
DECLARE @ID						UNIQUEIDENTIFIER= '17809210-7E80-49F6-BE5A-E10CD8FA1238';
DECLARE @GRUPPE					VARCHAR(100)	= 'Naturdata';
DECLARE @TEMA					VARCHAR(100)	= 'Overvågning af fugle, punkt';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Overvågning af fugle - punkter
OVERVAAGN_FUGLE_PKT';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 1;
DECLARE @UDBYDER				VARCHAR(100)	= 'DAI';
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= 'Indeholder data, som benyttes i henhold til vilkår for brug af danske offentlige data';
DECLARE @SOURCEURL				VARCHAR(100)	= 'http://arealdatamapping.blob.core.windows.net/geocortex/OVERVAAGN_FUGLE_PKT_SHAPE.zip';
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'overvaagn_fugle_pkt';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'ogr_fid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'aktivitets';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19900101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 7;

-- Hjælpe SQL til brug for dannelse af regionsspecifikke opdateringer
-- UPDATE _REGDEF SET  Bornh=0, RNord=0, RMidt=1, RSyd=0, RHoved=0, RSjael=0 WHERE TemaId='17809210-7E80-49F6-BE5A-E10CD8FA1238'

IF ($(RegionKode) IN (-1,1082))
BEGIN
    PRINT 'Naturdata: Overvågning af fugle, punkt'
	IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
	BEGIN
		INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
		VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
	END ELSE BEGIN
		UPDATE PROD.TemaMetaData
		SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID, OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
		WHERE ID = @ID;
	END;
END;
GO

