-- TemaMetadata tabellen i temadatabasen

use TemaDB
go


-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) EF fuglebeskyttelsesområder
/*
-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= 'A6BA873B-C9EA-4AA3-8FB2-116757284D26';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) EF fuglebeskyttelsesområder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'fugle_bes_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'OBJECTID';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'OBJEKTNAVN';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190527';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 10;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
*/
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) EF habitatområder
/*
-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '5DAC039D-1416-4C1E-B76A-C58D6F633F4E';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) EF habitatområder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'habitat_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'OBJECTID';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'OBJEKTNAVN';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190527';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 10;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
*/
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Indvindingsoplande i OSD

-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '0A8977F0-CF49-40EB-BF83-7B6CA4E6B230';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Indvindingsoplande i OSD';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Testdata sakset fra JAR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'e_gis_osd';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'pkid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'geom';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'navn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20181015';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 30;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Kirkebyggelinier
/*
-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= 'FEE0A117-422A-4C46-97DD-5F54806896BC';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Kirkebyggelinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'kirkebyggelinjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'OBJECTID';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= NULL;
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190527';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 60;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
*/
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Natura 2000

-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '83A16FDE-C757-45D4-9C33-88B06EB9DBD1';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Natura 2000';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Testdata sakset fra JAR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'e_gis_natura2000';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'pkid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'geom';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'navn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19000101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 30;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) overfladevand

-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '1AC32E7E-668D-4FB0-9767-243BC1D7DE08';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) overfladevand';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Testdata sakset fra JAR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'e_gis_overfladevand';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'pkid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'geom';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'type';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '19000101';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 30;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Ramsar områder
/*
-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '24BD48CE-7E73-4F64-9BE3-481EBB91284E';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Ramsar områder';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'ramsar_omr';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'OBJECTID';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'OBJEKTNAVN';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190527';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 20;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
*/
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Søbeskyttelseslinier
/*
-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= 'C7DF071B-476D-43EE-87AE-862E9451DD4C';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Søbeskyttelseslinier';
DECLARE @BESKRIVELSE			VARCHAR(100)	= '';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'soe_bes_linjer';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'OBJECTID';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'GEOM';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= NULL;
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20190527';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 20;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO
*/
-------------------------------------------------------------------------------------------------------
-- TEMA: (TEST) Vandværksoplande

-- GRUPPE: TESTDATA
DECLARE @ID						UNIQUEIDENTIFIER= '2D404F13-794C-4F1F-BBB3-D0D3F43AF74D';
DECLARE @GRUPPE					VARCHAR(100)	= 'TESTDATA';
DECLARE @TEMA					VARCHAR(100)	= '(TEST) Vandværksoplande';
DECLARE @BESKRIVELSE			VARCHAR(100)	= 'Testdata sakset fra JAR';
DECLARE @AUTOOPDATERINGAKTIV	BIT				= 0;
DECLARE @UDBYDER				VARCHAR(100)	= NULL;
DECLARE @COPYRIGHTBESKED		VARCHAR(100)	= '(c) CopyRight besked der skal vises';
DECLARE @SOURCEURL				VARCHAR(100)	= NULL;
DECLARE @SOURCEUSER				VARCHAR(100)	= NULL;
DECLARE @TABELNAVN				VARCHAR(100)	= 'e_gis_vandvaerksoplande';
DECLARE @IDKOLONNENAVN			VARCHAR(100)	= 'pkid';
DECLARE @GEOMKOLONNENAVN		VARCHAR(100)	= 'geom';
DECLARE @TEKSTKOLONNENAVN		VARCHAR(100)	= 'vandvaerksnavn';
DECLARE @ISVALID				BIT				= 1;
DECLARE @OPDATERETDATO			DATETIME		= '20181015';
DECLARE @OPDATERINGSFREKVDAGE	INT				= 30;

IF NOT EXISTS (SELECT 1 FROM PROD.TemaMetaData WHERE ID = @ID)
BEGIN
   INSERT INTO PROD.TemaMetaData (ID,GRUPPE,TEMA,BESKRIVELSE,AUTOOPDATERINGAKTIV,UDBYDER,COPYRIGHTBESKED,SOURCEURL,SOURCEUSER,TABELNAVN,IDKOLONNENAVN,GEOMKOLONNENAVN,TEKSTKOLONNENAVN,ISVALID,OPDATERETDATO,OPDATERINGSFREKVDAGE)
   VALUES (@ID,@GRUPPE,@TEMA,@BESKRIVELSE,@AUTOOPDATERINGAKTIV,@UDBYDER,@COPYRIGHTBESKED,@SOURCEURL,@SOURCEUSER,@TABELNAVN,@IDKOLONNENAVN,@GEOMKOLONNENAVN,@TEKSTKOLONNENAVN,@ISVALID,@OPDATERETDATO,@OPDATERINGSFREKVDAGE)
END ELSE BEGIN
	UPDATE PROD.TemaMetaData
	SET GRUPPE=@GRUPPE,TEMA=@TEMA,BESKRIVELSE=@BESKRIVELSE,AUTOOPDATERINGAKTIV=@AUTOOPDATERINGAKTIV,UDBYDER=@UDBYDER,COPYRIGHTBESKED=@COPYRIGHTBESKED,SOURCEURL=@SOURCEURL,SOURCEUSER=@SOURCEUSER,TABELNAVN=@TABELNAVN,IDKOLONNENAVN=@IDKOLONNENAVN,GEOMKOLONNENAVN=@GEOMKOLONNENAVN,TEKSTKOLONNENAVN=@TEKSTKOLONNENAVN,ISVALID=@ISVALID,OPDATERETDATO=@OPDATERETDATO,OPDATERINGSFREKVDAGE=@OPDATERINGSFREKVDAGE
	WHERE ID = @ID;
END;
GO




select * from PROD.TemaMetaData 
where isvalid=1
order by ISVALID desc, gruppe, tema

select * from PROD.TemaMetaData 
where isvalid=0
order by ISVALID desc, gruppe, tema